# Generated by Django 4.0.6 on 2022-07-16 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_user', '0001_initial'),
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answered_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answered_user', to='trivia_user.user'),
        ),
    ]
