version: '3.10'
services:
  client:
    restart: always
    build:
      context: .
      dockerfile: ./trivia_client/Dockerfile
    ports:
      - "4200:4200"
    entrypoint:
      - ./angular-entrypoint.sh
    depends_on:
      - db
    working_dir: /home/node/app
    volumes:
      - ./trivia_client:/home/node/app
      - node_modules:/home/node/app/node_modules

  api:
    restart: on-failure
    volumes:
      - ./trivia_app:/app
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - ./trivia_app/.env
    entrypoint:
      - ./django-entrypoint.sh
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  fastapi:
    restart: always
    volumes:
      - ./trivia_microservice:/app
    build:
      context: .
      dockerfile: ./trivia_microservice/Dockerfile
    env_file:
      - ./trivia_microservice/.env
    entrypoint:
      ./fast-api-entrypoint.sh
    depends_on:
      - redis
    ports:
      - "8080:8080"

  redis:
      image: redis:6.2-alpine
      ports:
        - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    env_file:
      - ./trivia_microservice/.env
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    env_file:
      - ./trivia_microservice/.env


volumes:
  postgres_data:
  node_modules:
