version: '3.10'
services:
  web:
    restart: on-failure
    volumes:
      - ./trivia_app:/app
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - ./trivia_app/.env
    entrypoint:
      - ./django-entrypoint.sh
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: docker-triviadb
      POSTGRES_PASSWORD: postgresstriviadocker
      POSTGRES_DB: triviaappdb
    ports:
      - "5432:5432"


volumes:
  postgres_data: